---
abstract: 'Modern Perl IDE'
author:
  - 'Ahmad M. Zawawi <ahmad.zawawi@gmail.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::EOL: '1.5'
  Test::MinimumVersion: '0.101080'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Farabi
no_index:
  directory:
    - t
    - xt
    - lib/Farabi/files
requires:
  Browser::Open: '0.04'
  Capture::Tiny: '0.21'
  Code::CutNPaste: '0.04'
  DBD::SQLite: '1.37'
  DBIx::Simple: '1.35'
  Debug::Client: '0.25'
  File::Find::Rule: '0.33'
  File::HomeDir: '1.00'
  File::Which: '1.09'
  IO::String: '1.08'
  IPC::Run: '0.92'
  Minilla: v0.4.6
  Module::Pluggable: '4.5'
  Module::Starter: '1.60'
  Mojolicious: '4.63'
  Moo: '1.000008'
  Parse::ErrorString::Perl: '0.18'
  Path::Tiny: '0.013'
  Perl::Critic: '1.118'
  Perl::Strip: '1.1'
  Perl::Tidy: '20121207'
  Reply: '0.07'
  Spellunker: v0.0.17
  perl: '5.010001'
resources:
  bugtracker: https://github.com/azawawi/farabi/issues
  homepage: https://github.com/azawawi/farabi
  repository: git://github.com/azawawi/farabi.git
version: '0.45'
