---
abstract: 'Modern Perl editor'
author:
  - 'Ahmad M. Zawawi <ahmad.zawawi@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Farabi
no_index:
  directory:
    - t
    - inc
    - xt
    - lib/Farabi/files
requires:
  Capture::Tiny: 0.21
  Code::CutNPaste: 0.04
  DBD::SQLite: 1.37
  DBIx::Simple: 1.35
  File::Find::Rule: 0.33
  File::Which: 1.09
  IO::String: 1.08
  IPC::Run: 0.92
  Module::Pluggable: 4.5
  Mojolicious: 3.36
  Moo: 1.000008
  Perl::Critic: 1.118
  Perl::Tidy: 20120714
  Test::EOL: 1.5
  Test::More: 0.98
  perl: 5.010001
resources:
  bugtracker: https://github.com/azawawi/farabi/issues
  homepage: https://github.com/azawawi/farabi
  license: http://dev.perl.org/licenses
  repository: git://github.com/azawawi/farabi.git
version: 0.31
