---
abstract: 'A web-based Perl editor'
author:
  - 'Ahmad M. Zawawi <ahmad.zawawi@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Farabi
no_index:
  directory:
    - t
    - inc
    - t
    - xt
    - eg
    - share
    - inc
requires:
  Mojolicious: 3.36
  Perl::Critic: 1.118
  Perl::Tidy: 20120714
  Pod::Index: 0.14
resources:
  bugtracker: http://code.google.com/p/farabi/issues/list
  homepage: http://code.google.com/p/farabi/
  license: http://dev.perl.org/licenses/
  repository: http://farabi.googlecode.com/svn/trunk/
version: 0.05
